POST http://localhost:3001/api/notes 
Content-type: application/json

{
  "content":"seguir con la certificacion de google",
  "important":true
}

###

POST http://localhost:3001/api/notes 
Content-type: application/json

{
}