POST http://localhost:3001/api/notes 
Content-type: application/json

{
  "content":"seguir con la certificacion de google",
  "important":true,
  "userId": "62e6c13b13dc92c7131d6acf"
}

###

POST http://localhost:3001/api/notes 
Content-type: application/json

{
}